### ISSUE TITLE
Quick question on benchmarking

### ISSUE THREAD

**Issue by koaning** [jcblaisecruz02/Filipino-Text-Benchmarks#8]
Hi there, nice repo! 

I work for [rasa](https://rasa.com/) and I've taken it up for myself to add more and more support for Non-English models. I've had a look at your paper and I was wondering ... is there a reason why you didn't include a count vector model? Is there something about the Filipino language that makes token-based bag-of-word models insufficient as a strategy?

**Comment by jcblaisecruz02** [comment]
Hi @koaning ! Thanks for the question.

Just as with most languages, bag-of-word models are sufficient for small tasks. But as tasks get increasingly complex (like for natural language understanding), they fall off in performance. Bag-of-words and count-based strategies are frequency-based techniques, and they do not have a way to represent meaning, word dependency, or linguistic concepts. The main point of using pretrained models (and the pretrained embeddings that came before them) is essentially this--richer representations of text. 

As to answer the question about Filipino: bag-of-words won't underperform because of any property of Filipino (or any language for that matter), it would underperform for complex tasks simply because it's not a very strong means of representation. Negation, for example, bag-of-words cannot represent how the word "not" in "not good" alters the sentiment of the word "good" since it doesn't have a notion of sequentiality in the first place. The capability to represent negation scope (and other linguistic structures) is important in various NLU tasks. Since frequency-based/count-based models can't do this, we don't really consider using them.

I hope I was able to answer your question! Let me know if there's anything else.

**Comment by koaning** [comment]
I agree with everything you said. But for classification tasks such as those in the dengue/hate-speech datasets, it can still be a valid benchmark, no? When I look at the table found in [this article](https://arxiv.org/pdf/2005.02068.pdf): 

![image](https://user-images.githubusercontent.com/1019791/101485103-f7132900-395a-11eb-863f-f15a69869a48.png)

it seems like simple bag-of-words were omitted. Any reason why? 

Anyway ... the main thing I should mention: it's awesome to see repositories like this one. Would you mind if I send community members interested in making chatbots to this resource?

**Comment by jcblaisecruz02** [comment]
Ah I see you were referring to the dengue and hatespeech datasets. We did test with simpler methods (bag of words, TF-IDF, naive bayes, etc) while we were running the experiments, thought they all either underperformed or required a lot of preprocessing since the raw data is pretty dirty. I do agree that they can be added! Perhaps we can show how much of a difference different families of techniques have in terms of performance. We'll consider it for our future benchmarks!

As for sending the repo to community members: Sure! No worries. We open source our work so that more people can benefit from them :) 

Let me know if I can help with anything else!
